"""initial schema

Revision ID: 2f38e7f18d1b
Revises: 
Create Date: 2026-05-09 13:11:05.804602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2f38e7f18d1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mappings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('upload_tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_no', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('progress_pct', sa.SmallInteger(), nullable=False),
    sa.Column('progress_msg', sa.Text(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('celery_task_id', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending','running','success','failed')", name='ck_uptask_status'),
    sa.CheckConstraint('progress_pct BETWEEN 0 AND 100', name='ck_uptask_progress'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_uptask_status_started', 'upload_tasks', ['status', 'started_at'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_no', sa.Text(), nullable=False),
    sa.Column('mapping_id', sa.BigInteger(), nullable=False),
    sa.Column('f_start_ghz', sa.Float(), nullable=True),
    sa.Column('f_end_ghz', sa.Float(), nullable=True),
    sa.Column('deembedded', sa.Boolean(), nullable=False),
    sa.Column('process_type', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_by', sa.Text(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("process_type IN ('S1P','S2P','BOTH')", name='ck_batch_proc_type'),
    sa.ForeignKeyConstraint(['mapping_id'], ['mappings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['upload_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_no')
    )
    op.create_index('idx_batches_mapping', 'batches', ['mapping_id'], unique=False)
    op.create_index('idx_batches_uploaded_at', 'batches', ['uploaded_at'], unique=False)
    op.create_table('mapping_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('mapping_id', sa.BigInteger(), nullable=False),
    sa.Column('mark', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eg', sa.Float(), nullable=True),
    sa.Column('fl', sa.Float(), nullable=True),
    sa.Column('ag', sa.Float(), nullable=True),
    sa.Column('area_s11', sa.Integer(), nullable=True),
    sa.Column('area_s22', sa.Integer(), nullable=True),
    sa.Column('has_pf', sa.Boolean(), nullable=False),
    sa.Column('raw_tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['mapping_id'], ['mappings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mapping_id', 'mark', name='uq_mentry_mapping_mark')
    )
    op.create_table('devices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('mark', sa.Text(), nullable=True),
    sa.Column('wafer', sa.SmallInteger(), nullable=True),
    sa.Column('folder_name', sa.Text(), nullable=True),
    sa.Column('coord', sa.Text(), nullable=True),
    sa.Column('x', sa.SmallInteger(), nullable=True),
    sa.Column('y', sa.SmallInteger(), nullable=True),
    sa.Column('eg', sa.Float(), nullable=True),
    sa.Column('fl', sa.Float(), nullable=True),
    sa.Column('ag', sa.Float(), nullable=True),
    sa.Column('pf', sa.CHAR(length=1), nullable=True),
    sa.Column('area_n', sa.Integer(), nullable=True),
    sa.Column('area_um2', sa.Integer(), nullable=True),
    sa.Column('fs_ghz', sa.Float(), nullable=True),
    sa.Column('fp_ghz', sa.Float(), nullable=True),
    sa.Column('zs_ohm', sa.Float(), nullable=True),
    sa.Column('zp_ohm', sa.Float(), nullable=True),
    sa.Column('qs', sa.Float(), nullable=True),
    sa.Column('qp', sa.Float(), nullable=True),
    sa.Column('qs_bodeq', sa.Float(), nullable=True),
    sa.Column('qp_bodeq', sa.Float(), nullable=True),
    sa.Column('dbqs', sa.Float(), nullable=True),
    sa.Column('dbqp', sa.Float(), nullable=True),
    sa.Column('bodeq_fitted', sa.Float(), nullable=True),
    sa.Column('bodeq_smooth', sa.Float(), nullable=True),
    sa.Column('bodeq_raw', sa.Float(), nullable=True),
    sa.Column('fbode_ghz', sa.Float(), nullable=True),
    sa.Column('k2eff_pct', sa.Float(), nullable=True),
    sa.Column('fp2_ghz', sa.Float(), nullable=True),
    sa.Column('fs2_ghz', sa.Float(), nullable=True),
    sa.Column('zp2_ohm', sa.Float(), nullable=True),
    sa.Column('zs2_ohm', sa.Float(), nullable=True),
    sa.Column('deembedded', sa.Boolean(), nullable=False),
    sa.Column('s_param_path', sa.Text(), nullable=True),
    sa.CheckConstraint("pf IN ('Y','N')", name='ck_device_pf'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dev_batch_wafer', 'devices', ['batch_id', 'wafer'], unique=False)
    op.create_index('idx_dev_coord', 'devices', ['coord'], unique=False)
    op.create_index('idx_dev_eg_fl_ag', 'devices', ['eg', 'fl', 'ag'], unique=False)
    op.create_index('idx_dev_mark', 'devices', ['mark'], unique=False)
    op.create_index('idx_dev_pf', 'devices', ['pf'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dev_pf', table_name='devices')
    op.drop_index('idx_dev_mark', table_name='devices')
    op.drop_index('idx_dev_eg_fl_ag', table_name='devices')
    op.drop_index('idx_dev_coord', table_name='devices')
    op.drop_index('idx_dev_batch_wafer', table_name='devices')
    op.drop_table('devices')
    op.drop_table('mapping_entries')
    op.drop_index('idx_batches_uploaded_at', table_name='batches')
    op.drop_index('idx_batches_mapping', table_name='batches')
    op.drop_table('batches')
    op.drop_index('idx_uptask_status_started', table_name='upload_tasks')
    op.drop_table('upload_tasks')
    op.drop_table('mappings')
    # ### end Alembic commands ###
